### ISSUE TITLE
Scenario.trend() phase visualization problems and runtime error

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#282] opened 2020-10-27 13:58 UTC
## Summary
- Scenario.trends() is not working properly for India, USA, Greece and Brazil. It doesn't show colored sections for phases in graphs:
![india_trends_noColor](https://user-images.githubusercontent.com/36845191/97311415-ffad1580-186c-11eb-9a1a-754c690afaac.png)
![usa_trends_noColor](https://user-images.githubusercontent.com/36845191/97311414-ff147f00-186c-11eb-86a9-07ed8e9b7b81.png)
![greece_trends_noColor](https://user-images.githubusercontent.com/36845191/97311410-fe7be880-186c-11eb-8951-bd827c2be009.png)
![brazil_trends_noColor](https://user-images.githubusercontent.com/36845191/97311403-fcb22500-186c-11eb-915c-c9e539123e1a.png)

- For Germany, upon trends() call, it throws error `RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 600.` and the trends() functionality doesn't work at all.
- For all the other countries I tested, trends() works normally as before.

## Related classes
- `covsirphy.Scenario`

## Codes and outputs:
country_scenario = cs.Scenario(jhu_data, population_data, "country")
country_scenario.records().tail()
_ = country_scenario.trend()

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Python, pip
- OS: Windows

**Comment by lisphilar** [comment] 2020-10-27 15:37
I fixed the runtime error with #285 with https://stackoverflow.com/questions/15831763/scipy-curvefit-runtimeerroroptimal-parameters-not-found-number-of-calls-to-fun

Please confirm it with development version 2.9.1-alpha.fix.282
```
pip install --upgrade "git+https://github.com/lisphilar/covid19-sir.git#egg=covsirphy"
```

> Scenario.trends() is not working properly for India, USA, Greece and Brazil. It doesn't show colored sections for phases in graphs

It's in the specifications #121 
Please change `Scenario.trend(max_rmsle=20)` to `Scenario.trend(max_rmsle=100)` etc.

However, we may have a room to improve it.
Could you help with me to find the root cause?
`Scenario.trend()` depends on `ChangeFinder` class.
https://github.com/lisphilar/covid19-sir/blob/master/covsirphy/phase/sr_change.py

**Comment by Inglezos** [comment] 2020-10-28 18:23
Yes the runtime error is fixed now in version 2.9.1-alpha.fix.282.
The underlying problem is why RMSLE scores for the phases recognition is that big. We would expect the trends to fit well the actual data curve, right? As they do well for the other countries.

**Comment by lisphilar** [comment] 2020-10-29 10:40
Sorry for not making it clear enough, but RMSLE score of Scenario.trend() is not the same as that of Scenario.estimate().
The steps of calculating RMSLE of trend analysis is as follows.
1. Perform curve fitting, x is Recovered, y is log(Susceptible)

**Comment by lisphilar** [comment] 2020-10-29 11:03
It appears that curve fitting was failed for Indea records etc. We should revise ChangeFinder class.

FYI, Call tree is as follows.
1. cs.analysis.scenario.Scenario.trend() calls cs.phase.phase_series.PhaseSeries.trend()
2.PhaseSeries.trend() calls cs.phase.sr_change.ChangeFinder.run(): find change points
3. PhaseSeries.trend() calls cs.phase.sr_change.ChangeFinder.show()
4. ChangeFinder.show() calls ChangeFinder._curve_fitting()
5. ChangeFinder._curve_fitting() calls cs.phase.trend.Trend.run(): Perform curve fitting
6. ChangeFinder._curve_fitting() calls cs.phase.trend.Trend.rmsle(): Calculate RMSLE score

**Comment by Inglezos** [comment] 2020-10-31 20:44
I am studying the code in order to find any weak spots for improvement/debug. For the time being I have some ideas to test:
i. in `sr_change.py` -> `run()`, keep more samples?
ii. at `rpt.Pelt()`, change `jump` size?
iii. in `algorithm.fit_predict()` call, change `pen`?
iv. change `min_size` from 7 to something smaller
v. in Trend class -> `_fitting()` change `maxfev`
vi. Another cost function instead of `rbf` for ruptures. Other good choices could be `normal`, `mahalanobis` or `rank`. Or create a new custom cost function (would be difficult)?

**Comment by lisphilar** [comment] 2020-11-01 13:39
> i. in sr_change.py -> run(), keep more samples?

Yes, incleasing sample size is a nice solution. I used the following codes to cut runtime, but I will try it.
```Python
# Sampling to reduce run-time of Ruptures
samples = np.linspace(0, series.index.max(), len(self.sr_df), dtype=np.int64)
series = series[samples]
```

> ii. at rpt.Pelt(), change jump size?

Documentation of Rutures says "`jump`: reduce the set of possible change point indexes; predicted change points can only be a multiple of jump."

I think this should be 1 as it is because we do not have information about how many change points are there.

> iii. in algorithm.fit_predict() call, change pen?

Possible.

> iv. change min_size from 7 to something smaller

Default value can be changed.

> v. in Trend class -> _fitting() change maxfev

This only fixes RuntimeError as discussed.

> vi. Another cost function instead of rbf for ruptures. Other good choices could be normal, mahalanobis or rank.

Tried, but failed.

> vii. A more general question: why do we study phases at the S-R plane specifically and not for example at the C(confirmed) - D(deaths) plane? Could we use another curve more effectively to apply trends analysis?

This is because (x, y) = (R, log(S)) are on a line for SIR, SIR-D, SIR-F, SIR-FV, SEWIR-F.
Please ensure to read
- https://lisphilar.github.io/covid19-sir/usage_phases.html#Set-phases-with-S-R-trend-analysis
- https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model#S-R-trend-analysis

> How can we see the trends() RMSLE scores?

As follows.
```Python
# Setting
import covsirphy as cs
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population
# Find change points
population = population_data.value(country="Japan")
sr_df = jhu_data.to_sr(country="Japan", population=population)
finder = cs.ChangeFinder(sr_df, min_size=7, max_rmsle=20.0)
finder.run()
# Get the start date and end date of a phase (e.g. 1st phase)
[
    cs.Trend(
        jhu_data.to_sr(country="Japan", population=population, start_date=start_date, end_date=end_date)
    ).rmsle()
    for (start_date, end_date) in zip(*finder.date_range())
]
# -> [0.00017165017964160256, 0.00011803137359578386, 4.346220556783464e-06, 5.094880108913458e-06, 2.124030851469172e-05, 4.769860659337155e-06, 2.410881918990526e-06, 2.4281797106340264e-06, 2.0745364412988465e-06, 1.8926126283957956e-06, 1.5375406407613923e-05]
```

**Comment by Inglezos** [comment] 2020-11-01 19:20
Yes, I am debugging this call tree and I added some print(RMSLEs) to get the scores.
I am working on some fixes and I believe I have found a solution for the trends issue we have. I will create a pull request tomorrow evening for that.

**Comment by lisphilar** [comment] 2020-11-02 12:58
I agree with your idea to use linear regression and thank you for your pull request!
I added some coments on it. Test codes will be in `tests/test_change_finder.py` (pytest) in this repository.

**Comment by Inglezos** [comment] 2020-11-04 09:29
Okay so after merging my changes/fixes, if your tests also confirm that now the trends analysis runs smoothly for various countries, I think we can close this issue. 
But first please inform me, what should I do in `tests/test_change_finder.py` file? What should I add?

**Comment by lisphilar** [comment] 2020-11-04 13:11
Thank you for your pull request and I merged it.
I created tests and I changed some codes to perform tests efficiently with .
- `Trend.run()` was renamed to `Trend._run()`
- New `Trend.run()` was created and this returns itself and this select the best function from "linear" and "negative exponential"

Sorry for update after merging your pull request.

**Comment by lisphilar** [comment] 2020-11-04 13:18
In `tests/test_change_finder.py`, We check if RMSLE scores of all phases are lower than set max value (20.0, this means colored line will be shown) in the listed countries.
Italy, japan, Indea, United States, Greece, Russia, Brazil, France, Spain, UK, New Zealand, Germany.

**Comment by lisphilar** [comment] 2020-11-04 14:24
Dear @Inglezos ,
Very sorry for bother you again.
I will merge #303 when all tests passed. If we need some changes in `Trend`, `ChangeFindeer` and test codes, please create pull requests or issues. Thank you.

**Comment by Inglezos** [comment] 2020-11-04 23:49
Sorry, I was busy these days at work. Yes sure, if I find any issue I'll let you know.

**Comment by lisphilar** [comment] 2020-11-05 09:15
Thank you for your discussion and pull request. I will close this issue.

**Closed by lisphilar** 2020-11-05 09:15 UTC
Labels: bug
