### ISSUE TITLE
[New] improve the way to calculate recovery period for recovered data full complement

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#420] opened 2020-12-15 23:55 UTC
## Summary of this new feature
I think it is a good idea to use `_recovery_period` combined with `calculate_closing_period()` for the final recovery period value. That is because valid linelist data are too few (only 277 values), compared to the total cases, they might not be very representative. That combination would mean for example an averaging of their mode values or averaging of their mean values or something like that.

**Comment by lisphilar** [comment] 2020-12-16 09:46
Because recovered period and closing period is different, we need to create a method for recovered period calculation. Recovered period can be estimated as the shift of `Confirmed - Fatal` and `Recovered`.

**Comment by Inglezos** [comment] 2020-12-16 14:43
We can separate closed cases into deaths and recoveries and to keep the recoveries. In the linelist data, there is a column "outcome", which states death/died for deaths and recovered/discharged for recoveries, for valid closing date. So we keep the mode/mean from these recovery dates and combine this with `calculate_closing_period()` current implementation (estimate recovery period also from other countries recovered data).

**Comment by lisphilar** [comment] 2020-12-16 15:13
The following steps?
- Calculate recovery period with linelist
- Calculate fatality period with linelist
- Calculate closing period with JHU-data
- Then, combine

Please create a pull request to discuss this issue deeply.

**Comment by Inglezos** [comment] 2020-12-16 16:10
Fatality period is not needed.
- Calculate recovery period with linelist
- Calculate recovery period with JHU-data (as is currently implemented in `calculate_closing_period()`
- Combine

**Comment by lisphilar** [comment] 2020-12-17 14:35
How do you combine recovery period and closing period...?

**Comment by Inglezos** [comment] 2020-12-17 15:23
By closing period you mean either fatal or recoveries right?
No closing period.
We use only recovery periods.
There are two recovery periods, one from linelist recoveries (in csv where outcome is discharged or recovered) and one from recoveries using `calculate_closing_period()`. We combine then these two by either averaging their mode values or themselves.

**Comment by lisphilar** [comment] 2020-12-17 15:28
> By closing period you mean either fatal or recoveries right?

Yes.

> recoveries using calculate_closing_period().

`calculate_closing_period()` calculates closing period, not recovery period. We calculate the shift of confirmed and recovered + fatal.

**Comment by Inglezos** [comment] 2020-12-17 16:14
Oh I had the impression this was only for the recovered.
Then we should change this too, for example comparing the confirmed minus fatal with recovered in order to find the future date where the pure confirmed are close to the recovered. This is possible right?

**Comment by lisphilar** [comment] 2020-12-18 16:44
I did not try this change today, but I think so.

**Comment by lisphilar** [comment] 2020-12-19 11:06
I got 17 days as recovery period using JHU data with the following steps.
https://gist.github.com/lisphilar/858a824b70c8700b879bd802ee29575e#file-recovered_period_20201219-ipynb

1. Find countries where recovery values are reported.
2. Calculate reovery period in each country (using `calc_r_period()` function In[17] of the notebook).
3. Calculate median value of step 2.

I will update `JHUData` class to calculate recovery period in this way.
It is not necessary to use the recovery period value calculated by `LinelistData` as default. Because data loading of `LinelistData` takes long time and much memory, it is better to use only JHU data for calculation of recovery period.

**Comment by Inglezos** [comment] 2020-12-19 11:55
Yes this seems acceptable value. Do you remember a 26 days value we found some time ago? Was that the closing day including fatal and recoveries or something else? For example in step 14 in the above results, it seems that there are two periods, almost 12 and 34 days. The improvement now is that we will calculate the period for all the valid countries individually and then combine in order to get a final period? Which results in 17?

**Comment by Inglezos** [comment] 2020-12-19 11:59
Could linelist be included if we preprocessor them once at the beginning of the analysis in order to save a final cleaned csv with only the few valid records? Then we could use load and process this every time instead of the big one.

**Comment by lisphilar** [comment] 2020-12-19 12:39
Yes, as you mentioned, the factor of improvement is that we use median value of recovery period in countries, not recovery period of total number of cases. Total number seems not represent the trend of countries.

Preprocessing of the raw data in `LinelistDaa._retrieve()` is a good idea, but I do not think we need the recovery period calculated with linelist as default. The value calculated with JHU data is representative relatively because JHU data has sufficient data.

**Comment by Inglezos** [comment] 2020-12-19 12:48
Yes this is because valid linelist are only few hundred records, otherwise it would worth a shot. Okay let's use only the JHU data then.

**Comment by lisphilar** [comment] 2020-12-19 13:38
Could you create a issue/pull request for preprocessing of linelist? Droping records with no country name/confirmation data.

**Comment by lisphilar** [comment] 2020-12-19 13:44
I created pull request #447 for this issue. Please review it.

- Add `JHUData.calculate_recovery_period()` to calculate recovery period with JHU data
- Full complement of recovery data in `JHUData` will use recovery period calculated with the method above as default in `DataLoader.jhu()`
- Deprecate `JHUData.calculate_closing_period()` (will be removed in the future, version 3.0.0)

**Comment by lisphilar** [comment] 2020-12-19 14:22
Update completed!

**Closed by lisphilar** 2020-12-19 14:22 UTC
Labels: enhancement
