### ISSUE TITLE
[New] data source for tests performed and vaccinations

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#429] opened 2020-12-17 18:07 UTC
## Summary of this new feature
Investigate new tests performed data source, as well as vaccinations source. I found this "Our World in Data" team:
https://github.com/owid/covid-19-data/tree/master/public/data.
Perhaps we could keep both test data and select a combination of them. Their test data seem to be more complete than JHU CSSE for some reason. Also this will be helpful as data source for the vaccinations; they already have such data.

**Comment by Inglezos** [comment] 2020-12-17 18:09
Dear @lisphilar,
When you have some time, please could you look into this?

**Comment by lisphilar** [comment] 2020-12-18 10:07
Notes:
Stable URL: https://covid.ourworldindata.org/data/owid-covid-data.csv
License:  Creative Commons BY license
Citation: Hasell, J., Mathieu, E., Beltekian, D. et al. A cross-country database of COVID-19 testing. Sci Data 7, 345 (2020). https://doi.org/10.1038/s41597-020-00688-8

**Comment by lisphilar** [comment] 2020-12-18 10:50
Thank you for information!!

<The number of tests>
Stable URL: https://covid.ourworldindata.org/data/testing/covid-testing-all-observations.csv
Useful columns:
- `ISO code`: ISO codes of countries (we need to convert them to country name)
- `Date`: Observation date
- `Cumurative total`: Cumurative number of tests (Interpolation is necessary)
- `Source URL`: Primary sources

We need to create `PCRData._cleaning_our_world_in_data()` method for data cleaning and set citations with `Source URL` column. `_cleaning()` method should remain (or rename to `_cleaning_data_hub()`) to use both of the datasets.
If this new dataset covers all countries registered in COVID-19 Data Hub with valid `Tests` records, we will use only this new dataset in `DataLoader.pcr()`.

**Comment by lisphilar** [comment] 2020-12-18 10:52
Notes:
The main dataset (https://covid.ourworldindata.org/data/owid-covid-data.csv) does not have source URLs for each values.

**Comment by lisphilar** [comment] 2020-12-18 12:12
For the number of tests, we will use `covid-testing-all-observations.csv` file, not `owid-covid-data.csv`. However, the detailed citation list will not be prepared because "Our World In Data" team collects records and we can regard "Our World In Data" as a primary source.

**Comment by Inglezos** [comment] 2020-12-18 12:24
Yes I completely agree. Can you see if they also have any recovered data more credible than the ones we already have? I mean for the countries we fully complement, if they somehow have these data. Even though I don't see any recovered data at all with a quick look.

**Comment by lisphilar** [comment] 2020-12-18 12:26
## The number of vaccinations
Because each vaccine has different value of effectivity, vaccine names are necessary information in our project. We will combine the two following CSV files.

1. vaccinations.csv
Stable URL: https://covid.ourworldindata.org/data/vaccinations/vaccinations.csv
Useful columns:
- `location`: Country or province names
- `date`: Observation dates
- `total_vaccinations`: Cumurative number of vaccination

2. locations.csv
Stable URL: https://covid.ourworldindata.org/data/vaccinations/locations.csv
Useful columns:
- `location`: Country or province names
- `date`: Observation dates
- `vaccines`: Company names of vaccines

`VaccinationData` will be created to handle this dataset and calculate `omega` of SIR-FV model (or a parameter of new model).

The structure of this dataset may be changed in the near future because the number of records is small at this time, but this is an useful dataset for us.

**Comment by lisphilar** [comment] 2020-12-18 12:30
> Can you see if they also have any recovered data more credible than the ones we already have?

In [owid-covid-codebook.csv](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv), recovered data was not found. "Our World In Data" does not include recovered data.

**Comment by lisphilar** [comment] 2020-12-20 08:26
With #451, I updated `PCRData` and `DataLoader` class to use the number of tests records of "Our World In Data" with priority.
```Python
pcr_data = DataLoder.pcr()
```

(The number of tests in China is not registered except for two records. `.positive_rate("China")` still raises `PCRIncorrectPreconditionError`.)

**Comment by Inglezos** [comment] 2020-12-20 13:37
Great I will test this later in the day. As I saw, you download this only if it does not exist. Maybe we should apply download necessity method, and download this if the last download date was 12 hours ago at least.

**Comment by Inglezos** [comment] 2020-12-20 13:38
So all the test records from JHU are overwritten by this source right? There is no combination of pre-existing values (e.g. averaging)

**Comment by lisphilar** [comment] 2020-12-20 15:10
With #429,
- `VaccineData` class and `DataLoader.vaccine()` will be added for data cleaning of vaccine data (the number of vaccinations).
- `VaccineData.subset()` will be added for subsetting.
- `VaccineData.total()`  will be added to calculate total values of vaccination.
- Document will be in https://lisphilar.github.io/covid19-sir/usage_dataset.html

**Comment by lisphilar** [comment] 2020-12-20 15:15
> Maybe we should apply download necessity method, and download this if the last download date was 12 hours ago at least.

Thank you. I will create a pull request to update `DataLoader.pcr()` method.

> So all the test records from JHU are overwritten by this source right? There is no combination of pre-existing values (e.g. averaging)

Yes, overwritten with `pandas.DataFrame.update()`. I think averaging will produce unexpected errors.

**Comment by Inglezos** [comment] 2020-12-20 19:25
I think we must include the column "Daily change in cumulative total" records as well and obtain test data from there too. Because for example Sweden does not have filled "Cumulative total" column, but has daily data which are obviously useful and can be used for the positive rate calculation.

**Comment by Inglezos** [comment] 2020-12-20 23:27
Also problems now exist for Italy and France. For Italy the positive rate plot is problematic for the last weeks, while for France upon executing `pcr_data.positive_rate("France")` it throws an error 
```
\scipy\interpolate\fitpack2.py:232: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
```
```
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

What is going on, please investigate this.

For France we need to stricten the check preconditions criteria. Please investigate the issue for Italy, I suspect it has something to do with the update method perhaps?
Before new dataloader test method:
![ita_daily_new_positive_rate](https://user-images.githubusercontent.com/36845191/102726996-9bb64300-432b-11eb-8ceb-600ad95a2cd0.jpg)
After new dataloader test method:
![ita_daily_new_positive_rate](https://user-images.githubusercontent.com/36845191/102726998-a7a20500-432b-11eb-9be4-d698521b110a.jpg)

**Comment by Inglezos** [comment] 2020-12-21 01:38
I am sure the update method is the cause. If I comment out the lines
```
        owid_filename = self.dir_path.joinpath(basename_owid)
        pcr_data.update_with_ourworldindata(filename=owid_filename)
```
in `dataloader.py`, then I get the first above normal results.
The two test sources (JHU CSSE and "our world in data") differ about Italy a lot.
I debugged this as follows: I put a breakpoint at line 189 `df.update(new_df)` inside `pcr_data.py` and executed the following codes:
```
!italy_df = df.loc[df["Country"] == "Italy"]
italy_df = italy_df.drop_duplicates(subset=[self.ISO3, self.DATE])
italy_df = italy_df.groupby(self.COUNTRY).filter(lambda x: x["Tests"].sum() != 0)
italy_df = italy_df.groupby(self.DATE).sum()

!new_italy_df = new_df.loc[new_df["ISO3"] == "ITA"]
```
and I got these results:
![image](https://user-images.githubusercontent.com/36845191/102730534-bb566700-433d-11eb-9fc5-bfab3c8af5c2.png)

**Comment by Inglezos** [comment] 2020-12-21 01:49
Regarding France, the problem is that there are only two unique test values which are filled the same, so diff is zero and thus the condition in `_pcr_processing()`
```
        df.loc[
            df[self.T_DIFF].abs() < df[self.C_DIFF].abs(), self.T_DIFF] = None
```
puts all fields to None and so the `non_zero_index_start` is set to NoneType. This should be covered in the check preconditions step. I am working on some stricter conditions in that method, I will create soon a pull request for this.

**Comment by Inglezos** [comment] 2020-12-21 02:05
I think I have found an explanation. It is rapid tests + PCR versus PCR.
If you see in https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv:
![image](https://user-images.githubusercontent.com/36845191/102731813-88ae6d80-4341-11eb-8b16-9f19a475ee94.png)
I think "tamponi" refers to all tests, including rapid, while "casi_testati" to PCR only, which are what the "our world in data" team finally uses -> refer to Italy section in https://ourworldindata.org/coronavirus-testing:
"Since September 2020, the Italian government has approved the use of antigen tests for the rapid diagnosis of COVID-19. It is unclear, however, whether those antigen tests are included in the data published on GitHub by the Department of Civil Protection. Several people have sought clarification (1, 2), and as of 7 December 2020 we are waiting for more information before setting the “test definition” for Italy."

**Comment by Inglezos** [comment] 2020-12-21 02:31
I have created pull request #454 for France issue.
I hope all these comments are relevant to this open issue. If we need to open a new issue please do so and move this discussion there. I just thought they were relevant because they began from this new data source open issue :)

**Comment by lisphilar** [comment] 2020-12-21 12:52
Thank you for your investigation and pull request!!

One solution is here.
- Use the dataset of COVID-19 Data Hub as default.
- Only when `PCRIncorrectPreconditionError` is raised in `PCRData._pcr_check_preconditions()`, retrieve the data from "Our World In Data" for the country and retry `PCRData._pcr_check_preconditions()` with this new dataset.

**Comment by Inglezos** [comment] 2020-12-21 13:08
Yes I agree. So two steps:
1. Only when `PCRIncorrectPreconditionError` is raised in `PCRData._pcr_check_preconditions()`, retrieve the data from "Our World In Data" for the country and retry `PCRData._pcr_check_preconditions()` with this new dataset.
2. First check "Cumulative total" column for data and if it does not have any, then move on to check "Daily change in cumulative total" records. (as I described in the first comment)

**Comment by lisphilar** [comment] 2020-12-21 15:33
I created pull request #455 for the first step. Please review it.

P.S.
Sorry, but I will not have coding time tomorrow because of business.

**Comment by Inglezos** [comment] 2020-12-21 17:31
Great, I merged it and will test it, thank you!

**Comment by Inglezos** [comment] 2020-12-22 02:37
I have found some problems.
1. The first one concerns the change from `df = before_df.fillna(...)` to `df[self.TESTS].fillna()` in some pcr methods. This is wrong, because these methods were meant to fill also `T_DIFF` values, not only `TESTS`.
2.  Also, in `PCRIncorrectPreconditionError._area()` we should now check for "-" for empty province, not just `None`. This leads to showing `PCRIncorrectPreconditionError:  Too many missing Tests records in province -.` while the correct error is showing the country name, for example `PCRIncorrectPreconditionError:  Too many missing Tests records in country France.`.

**Comment by Inglezos** [comment] 2020-12-22 02:50
I created pull request #457 for the two above problems.

**Comment by Inglezos** [comment] 2020-12-22 02:53
Now what remains is the second step with the "Cumulative total" column data.

**Comment by lisphilar** [comment] 2020-12-22 10:07
`df.groupby("ISO3 code")["Daily change in cumulative total"].cumsum()` will calculate the cumulative values.

**Comment by Inglezos** [comment] 2020-12-22 14:18
Yes, but this has to be done only for the countries that do not have filled existing cumulative total data

**Comment by lisphilar** [comment] 2020-12-22 14:29
How can we define unfilling of the data?

**Comment by Inglezos** [comment] 2020-12-22 14:35
If they have 0 or NaN values I guess. For example, you can see for Sweden (open manually `covid-testing-all-observations.xls` file, filter for country France and hide irrelevant columns) all the `Cumulative total` column cells are empty but the `Daily change in cumulative total` column cells are all filled.

**Comment by lisphilar** [comment] 2020-12-22 15:22
Sorry, I do not have my PC to see the file now.
With your information, we can divide the records using `.isna()` after replacement of zeros. Then, NA part will be updated with groupby/cumsum as I mentioned and ffill etc. The output will be combined with Non-NA part.

**Comment by lisphilar** [comment] 2020-12-24 15:46
I created pull request #458 for th idea I commented. Please review it.

- Calculate cumulative number of tests using daily data, if necessary. (PCR data with "Our World In Data")
- FIx a bug in PCR data cleaning (the number of tests were replaced with NA values in `use_ourworldindata` method).
- Add a test with Sweden data.

**Comment by Inglezos** [comment] 2020-12-24 16:06
I approved the changes. One question for clarification though:
>the number of tests were replaced with NA values
>
Is this the logic you followed?:
In cumulative and in daily tests replace nan with zeros first. Then check if some cumulative fields are empty and if so calculate the respective cumsum until that date from valid daily test records?
Because for example we may deal with partially filled either cumulative or daily test records. The code must be able to handle with both appropriately.

**Comment by lisphilar** [comment] 2020-12-24 16:21
This is just for a bug fixed with line 190 and 199 in the pull request, not for the new logic. Before country names and confirmed values were added the dataframe of the new data source, test values were saved temporarily as `series` variable with reset index. With this change, country_date will be used as the index of the series.

**Comment by Inglezos** [comment] 2020-12-25 02:03
Okay, so the new logic is implemented in commit "add: calculate cumsum if necessary in PCR data" right?
Is there any chance that a country can have partially cumulative and partially daily tests, like a mix of these two? Because I think that the code assumes we have only either the one or the other case, not a mix of both.

**Comment by lisphilar** [comment] 2020-12-25 10:09
> Okay, so the new logic is implemented in commit "add: calculate cumsum if necessary in PCR data" right?

Yes.

> Is there any chance that a country can have partially cumulative and partially daily tests, like a mix of these two?

How can we mix??

**Comment by lisphilar** [comment] 2020-12-25 10:15
Witch country needs mixing?

**Comment by Inglezos** [comment] 2020-12-25 12:42
Currently I don't see any such countries, it is just a thought, we can't know what data may appear in the future in these two columns.

**Comment by lisphilar** [comment] 2020-12-25 13:11
Hmm....we need to trust on the raw data unless we find inconsistancy. Can we merge #458?

**Comment by Inglezos** [comment] 2020-12-25 13:33
I agree. Yes merge it!

**Comment by lisphilar** [comment] 2020-12-25 14:42
#458 was merged, thank you!
This issue will be closed, if no issues found for vaccination data.

**Closed by lisphilar** 2020-12-25 14:42 UTC
Labels: New data loader, enhancement
