### ISSUE TITLE
[Docs] SIRS, SIRFS model not implemented

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#379] opened 2020-12-05 02:57 UTC
## Summary of this new feature
Since we already have SIR, SIRD, SIRF, SEWIRF, SIRFV, it would be useful to add SIRS and SIRFS as well, since we don't know for how long someone is immune.

**Comment by lisphilar** [comment] 2020-12-08 15:42
Yes, we should consider re-infection. However, we need new datasets to work with this idea.
Or, we may use SIRS-derived models for scenario analysis with user-defined re-infection rate value.
(SIRF-V model has same issue now.)

**Comment by Inglezos** [comment] 2020-12-08 17:11
To begin with, we should add these as example models (for theoretical data analysis) and then use user-defined re-infection rate value yes. However, won't the estimator auto-tune this rate? Why do we need extra datasets?

**Comment by lisphilar** [comment] 2020-12-09 16:10
Auto-tune can be applied as you mentioned. However, the number of parameters is too large againest the number of variables. This makes low accuracy as (or lower than) you see in SIR-F model.

**Comment by Inglezos** [comment] 2020-12-09 16:55
Hmm I see the problem yes. Okay we could add the example models to begin with and then we could have a user-defined parameter for reinfections yes.

**Comment by rebeccadavidsson** [comment] 2021-01-04 06:33
Maybe look at including the SEIR model? Although, there is some evidence that simpeler models can reach higher accuracy in terms of predicting the number of cases. This could be explained by the fact that using more complex models (such as the SEIR model) will produce a loss of information compared to the 'simpeler' SIR model. However, it was found that the SEIR model can in fact reach higher prediction accuracy, but only in certain countries (https://www.researchsquare.com/article/rs-85513/v1), highlighting the potential of the SEIR model.

**Comment by lisphilar** [comment] 2021-01-04 12:41
Thank you for your comment.
"Exposed" is included in SEWIR-F model and our complex model could be SEWIR-FVS model.

- Susceptible -> Exposed -> Waiting (=Infective but not confirmed) -> Infected (Confirmed) -> Recovered
-  Infected -> Fatal
- Waiting -> Fatal
- Susceptible -> Vaccinated
- Recovered -> Susceptible

This is similar to Figure 3 in the paper you mentioned.

This model will not suit for parameter estimation, but this will be useful for forcasting the number of cases if we can calculate the parameter values with new datasets.

**Comment by lisphilar** [comment] 2021-02-16 15:12
As dicussed in #573, SIR-F model could be the final model in our data-driven approach.
For "Recovered -> Susceptble",
1. If re-infected case is counted as a new confirmed case and removed from "Recovered" compartment, sigma will be decreased.
2. 1. If re-infected case is counted as a new confirmed case and NOT removed from "Recovered" compartment, rho will be increased because "Susceptible" will be decreased.

I do not know how counted in each country, but I can conclude that re-infection could be observed with parameter values.

**Comment by lisphilar** [comment] 2021-02-28 15:42
This will be documented in https://lisphilar.github.io/covid19-sir/usage_theoretical.html

**Closed** 2021-02-28 16:34 UTC
Labels: enhancement, good first issue
