### ISSUE TITLE
[Discuss] evaluation tool of impact of interventions including vaccination

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#644] opened 2021-03-02 15:05 UTC
## Summary of this new feature
How to evaluate the impact of interventions, including vaccination will be discussed here. As an example, ~~intercept~~ **coefficient** of regression model (Elastic Net, X=OXCGRT indicators/Vaccinations/Tests, y=parameter values of SIR-derived models) will be useful. When absolute values of ~~intercept~~ **coefficient** were high, the indicators are important to change parameter values.

**Comment by lisphilar** [comment] 2021-03-02 15:07
It will be great to evaluate the infectivity, effectivity and safety of vaccinations.

**Comment by lisphilar** [comment] 2021-03-02 15:17
Intercept values with Israel data (vaccination speed is high):

https://gist.github.com/lisphilar/43dcaf7cb3b712b79a56a7d923047908

|  | School_closing | Workplace_closing | Cancel_events | Gatherings_restrictions | Transport_closing | Stay_home_restrictions | Internal_movement_restrictions | International_movement_restrictions | Information_campaigns | Testing_policy | Contact_tracing | Tests | Vaccinations | Vaccinated_once | Vaccinated_full
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
theta | 0.037970 | -0.012397 | -0.012977 | -0.018872 | 0.004200 | -0.002500 | 0.004323 | 0.008660 | 0.000000 | 0.005325 | 0.009943 | -0.048809 | 0.054250 | 0.007399 | -0.025603
kappa | 0.000614 | 0.000065 | -0.000128 | -0.000301 | -0.000129 | -0.000473 | 0.000237 | 0.000041 | 0.000000 | -0.000043 | 0.000082 | -0.000627 | 0.000881 | 0.000261 | -0.000904
rho | 0.034813 | -0.058142 | -0.037992 | -0.000358 | 0.025022 | 0.063343 | -0.014796 | 0.012640 | 0.000000 | 0.030916 | 0.018413 | 0.080806 | -0.070115 | 0.002165 | -0.007490
sigma | -0.039210 | 0.047933 | 0.029230 | 0.016711 | -0.016174 | -0.043662 | 0.007245 | -0.023219 | 0.000000 | -0.020257 | -0.019543 | 0.111501 | -0.072282 | -0.009645 | 0.033374

**Comment by Inglezos** [comment] 2021-03-05 09:49
Are negative values supposed to occur for the parameters? Do these intercept values indicate relative change compared to previous state? Because if not, then they always must be positive.

**Comment by lisphilar** [comment] 2021-03-05 09:58
Negative values are supposed and suggest these indicators reduce the parameter values. "Intercept" is the intercept of regression equations.

**Comment by Inglezos** [comment] 2021-03-05 14:36
So they are the constant value added to constructed regression line of the format y = a*x + b. But why are they so important and we study these? How are they interpreted? The theory says that the intercept value is the y-axis value when x=0. So for example how is this applied to the first value 0.037970? Is it x = school closing and y = theta? Then x=school closing=0 means no measures? So if we have no measures (x=0), then theta will get increased by the intercept value 0.037970 during the forecasted phase?
Sorry for the silly questions perhaps, but I need to get a grasp on this prediction mechanism.

**Comment by lisphilar** [comment] 2021-03-05 14:57
”Elastic net regression" is a upgraded version of multiple regression analysis, y = a0 + a1 * x1 + a2 * x2 +....

By mistake in translating terms, I used "intercept" for ”coeficient". Very very sorry for confusing you. I will fix documentation and docstring later.

In the theta case above,
"theta" = (y-intercept) + 0.037970 * School_closing  - 0.012397 *  Workplace_closing.....

"Y-intercept" is not shown in the dataframe. Only coefficients values are there. Coeffieint values suggest the impact of the indicators.

**Comment by rebeccadavidsson** [comment] 2021-03-15 09:13
Using MultiTaskElasticNetCV in the fit() method, isn't this also highly dependent on the variation in input data? So for example, here is just a scenario: in country X, gatherings restrictions are only applied for 1 week. In this week the model parameter bèta could have been really high. In this case, this method would indicate that gatherings restrictions were very ineffective, since contact rate was only rising. However, if gatherings restrictions were applied for 3 months, average contact rate could have resulted in a much lower value. Of course there is no way (yet) of calculating the exact coefficients but maybe there has to be some kind of compensation for the length of each intervention and, another topic but also very hard to adjust for, interference/overlap with other interventions.

**Comment by lisphilar** [comment] 2021-03-15 09:53
We tried to put the inpact of delay effect and length of intervations in the regression, but, as you said, the outputs highly depends on the variations of input data because we have only small data for fitting.

We have two options.
1. Peform parameter estimation faster and run estimation for many countries.
2. Change regression model from Elastic Net. Could Neural Net be an alternative?

**Comment by lisphilar** [comment] 2021-03-15 10:00
Dear @rebeccadavidsson ,
An additional question regarding this issue.
How can we evaluate quantitatively that the regression model considers the length of each intervention accurately?

**Comment by rebeccadavidsson** [comment] 2021-03-15 10:09
I would think that running estimations for multiple countries would only result in more interference, since interventions are followed in various ways. 
And @lisphilar, the length of each intervention is known, such as when stringency score of gatherings restriction rises to a score of 3 and then falls back to 0 after lets say 10 weeks. The timing of those weeks, where score of an intervention was higher than 0 indicates the duration of an intervention. So this could be used to filter out these periods/days for each intervention in order to get the remaining length, which can be used as an indication of how accurate the regression model for that intervention is? Just an idea, I don't know if it helps.

**Comment by lisphilar** [comment] 2021-03-15 10:33
Just to confirm, do you mean that the regression model should learn the relationship of the delayed length of intervention (X) and the parameter values?
The current regression model learns that of the delayed indicator scores (X) and the parameter values.

**Comment by rebeccadavidsson** [comment] 2021-03-15 12:28
I mean that the level of uncertainty could be quantified by calculating the amount of input data for each intervention, including the lengths of each intervention. That the confidence of coefficient estimation is lower for interventions that were very short. And that can be done aside from the method of the current regression model, that is based on the indicator scores and parameter values.

**Comment by lisphilar** [comment] 2021-03-15 14:06
That is an interesting idea and it could be implemented as method(s) of `Scenario` and `OxCGRTData` class.

**Comment by lisphilar** [comment] 2021-03-15 14:37
Could you start a new issue/pull request for `OxCGRTData` (pytest: tests/test_cleaning/test_oxcgrt.py, docs: example/usage_dataset.ipynb)?
Methods of `Scenario` class will be discussed here later, if `Scenario` needs a method for that.

**Comment by lisphilar** [comment] 2021-04-13 10:01
Memo for feature importances, selection, engineering:
 https://link.medium.com/ulhWzK13pfb

**Comment by lisphilar** [comment] 2021-05-17 14:44
- Show corr (absolute values of corr) of ODE parameter values and interventions using bar plots.

**Comment by lisphilar** [comment] 2021-05-25 11:32
> I mean that the level of uncertainty could be quantified by calculating the amount of input data for each intervention, including the lengths of each intervention. That the confidence of coefficient estimation is lower for interventions that were very short. And that can be done aside from the method of the current regression model, that is based on the indicator scores and parameter values.

@rebeccadavidsson ,
Could we implement this qualification with the following new method of `OxCGRTData` (not implemented currently)?

- Calculate score times length for each intervention
- Sort them by values
- Show them with a bar plot
- Highlight the ongoing value

**Comment by lisphilar** [comment] 2021-06-28 12:27
The number of elapsed days from indicator change points is considered as a feature of regression model with #842 and this issue was partially solved.

**Closed** 2021-06-28 12:27 UTC
Labels: brainstorming
