### ISSUE TITLE
Training/Test dataset split - evaluation metrics & accuracy

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#276] opened 2020-10-26 03:32 UTC
## Summary of question
- Does there exist a feature which we can use to freeze the incoming data at a specific date, for example 15Sep20 and use the data up to that date as the "training" set, in order to make future predictions for 16Sept20 and after up until now 26Oct20 (I mean up until a date that we have also data)?
Is something like that possible and available in the current version? The rest data until now (for example 16Sepet20 - 26Oct20) should be ignored for the "training" set and considered as the "test" set. This would enable us to measure the model's accuracy and perform validation metrics.
- I just noticed that you have a function called estimate_accuracy(). Does this provide the same functionality as what I describe?

## Environment
- CovsirPhy version: 2.9.1
- Python version; 3.8
- Installation: Anaconda, Spyder, pip
- OS: Windows

**Comment by lisphilar** [comment] 2020-10-26 16:08
Yes, we can do it with Scenario class. I call it as "Retrospective analysis".
Please refer to https://lisphilar.github.io/covid19-sir/usage_quick.html#Retrospective-analysis

**Comment by lisphilar** [comment] 2020-10-26 16:10
Please do not mix prediction and simulation.
I used "Predicted number of cases" as the title of `Scenario.simulate()`, but this is not correct. I will revise it.

**Comment by Inglezos** [comment] 2020-10-26 16:45
> Yes, we can do it with Scenario class. I call it as "Retrospective analysis".
> Please refer to https://lisphilar.github.io/covid19-sir/usage_quick.html#Retrospective-analysis

Retrospective analysis is a very useful feature indeed, but I don't think I meant exactly that...

Let's say I simulate Italy today, 26Oct20, for the next 7 days, because I want to predict the future confirmed and death cases. Now, beforehand, I cannot assess how well, how accurate the model will make those predictions for the next week, since I don't have now the future actual data obviously. I have to wait one week, and then _retrospectively_ compare for each day, the actual confirmed cases with the predicted/simulated and the actual death cases for the predicted/simulated ones, calculate the RMSLE and conclude the accuracy of the model.

This could be done at another time window. If we assume now is 2Nov20 and we cutoff the data input to CovsirPhy up until 26Oct20 and run the simulation for one week, then now, 2Nov20, since we already have the actual data, we can compare right away the predictions with the actual data and conclude about the model's accuracy.

I hope I didn't confuse you. Are we saying the same thing? Or the existing retrospective analysis feature does exactly that?


> Please do not mix prediction and simulation.
> I used "Predicted number of cases" as the title of `Scenario.simulate()`, but this is not correct. I will revise it.

The simulation of cases for a country, isn't the same thing as making predictions for the future cases for this country? What is their difference?

**Comment by lisphilar** [comment] 2020-10-27 14:09
Please read the following. Is this your point?
Please replace "26Oct2020" with "02Nov2020" and replace "01Sep2020" with "26Oct2020" in your question/suggestion.
```Python
snl = cs.Scenario(...)
# we have records to 26Oct2020, but we use the records to 01Sep2020 for parameter estimation
snl.retrospective("01Sep2020", model=cs.SIRF, control="Main", target="Retrospective")
```
Show the history of Reproduction number.
```Python
snl.history("Rt")
````
![usage_quick_67_0](https://user-images.githubusercontent.com/7270139/97310666-cf826880-18a6-11eb-8936-fb6ba31940a7.png)

In main scenario, Rt changes after 01Sep2020 because parameter estimation was done.
In retrospective scenario, Rt does not change after 01Sep2020 because parameter estimation was not done.

Show the history of Infected.
```Python
snl.history("Infected")
````
![usage_quick_68_0](https://user-images.githubusercontent.com/7270139/97311427-af06de00-18a7-11eb-88c9-042c876f3833.png)

In main scenario, Infected changes with SIR-F model and the parameter values estimated with the actual data.
In retrospective scenario, Infected changes after 01Sep2020 with SIR-F model and the parameter values on 01Sep2020.


> The simulation of cases for a country, isn't the same thing as making predictions for the future cases for this country? What is their difference?

SIR-drived models are based on ODEs. With a specific parameter set and initial values, the number of cases is determined uniquely.
We can estimate the parameter values with acual records and predict the parameter values (with the current values of parameters and OxCGRT values etc.), but it is difficult to predict the the number of cases directly because the number of cases does not depend on the past values of number of cases directly.

Because parameter values are changed phase-dependently, we cannot calculate the accuracy of the model. RMSLE depend on all of the accuracy of models, that of parameter estimation tools, and parameter values for provided actual records.

**Comment by Inglezos** [comment] 2020-10-28 00:15
- Okay, so the retrospective curve is, let's say essentially, our "predictions", having frozen the parameters at that date and simulating the cases progress in the future based on those frozen parameters. While, on the other hand, the main curve, is what the actual data were. So, if we want an "accuracy", that would be the difference of these two curves, right? Yes, that's what I wanted.
- But as you say, something like that does not make sense. Any predictions, because they are based on the current parameters we managed to estimate from the current actual data, change in every phase as the time passes and any projection of the cases into the future, any cases _predictions_, are not valid actually. Do I understand this correctly?

**Comment by lisphilar** [comment] 2020-10-28 15:25
Please read #288 and #3 in advance. Let's discuss the definition of terms in #288.
Then, my comments are as follows.

> But as you say, something like that does not make sense. Any predictions, because they are based on the current parameters we managed to estimate from the current actual data, change in every phase as the time passes and any projection of the cases into the future, any cases predictions, are not valid actually. Do I understand this correctly?

Yes. We need to separete "prediction of parameters" and "simulation of the number of cases with frozen parameter values".

> Instead of an accuracy metric then, would it be better to keep the RMSLE score? Are RMSLE scores representative of the model's effectiveness?
> So, if we want to improve the model's "accuracy", for better cases predictions, which is equivalent with better parameters estimation, what do we need to do?

We have three typew of accuracy, "accuracy of models", "accuracy of trend analysis", "accuracy of parameter estimation". RMSLE scores with actual data cannot evaluate the three types of accuracy separately.
At this time, I don't have ideas to evaluate "accuracy of models" out of the three types.

Calculation of RMSLE scores with theoritical data (discussed in #279 and https://github.com/lisphilar/covid19-sir/blob/master/example/sirf_model.py) removes "accuracy of trend analysis" because the trend (set of parameter values) does not change.

**Comment by Inglezos** [comment] 2020-10-28 20:47
Please answer me at #279 as well, but what would such theoretical data be, what do you mean? Essentially, if we simulate the model based upon the latest phase and the frozen estimated variables, then we have the simulated cases, which we can compare against the actual ones. The theoretical data you propose, if I understand correctly, would be generated in the same way using the country's population and these parameters, so.. could they be the same thing? Or do you mean something different completely?

**Comment by lisphilar** [comment] 2020-10-29 14:41
I added a comment on #279 regarding the first test.

> theoritical data

This is an example data which has only one phase and follows a SIR-derived model. The parameter set is not the parameter set estimated with actual data. 
https://lisphilar.github.io/covid19-sir/usage_theoretical.html

> Or do you mean something different completely?

Something different.
The difference between theoritical data and actual data is that the parameter set of the first one does not based on actual records.

> accuracy of parameter estimation

Did you mean you want to the following test?
Please assume that the last date of actual records is 29Oct2020.
1. Perform trend analysis
2. Perform parameter estimation with the actual records of the last phase
3. Simulate the number of cases from 30Oct2020 to 30Nov2020 with the fix parameter values estimated with the last phase
4. Wait until 30Nov2020
5. Compare actual number of cases from 30Oct2020 to 30Nov2020 and simulated number of cases from 30Oct2020 to 30Nov2020
6. Calculate the difference of them

Because step 3 is an extrapolation, the score calculated in step 6 does not show accuracy.

Details ate here.
The parameter set on 30Oct2020 may be the same as that on 29Oct2020 as you considered.
However, that on 30Oct2020 may be different from that on 29Oct2020 because government responses and actions taken by people may change the parameter set.
This means that, as well as errors of parameter estimation, government responses and actions can raise the difference of the number of cases between actual and simulated values.
So, we cannot evaluate the accuracy of parameter estimation only with the comparison of actual values and simulated values using fixed parameter set.

**Comment by Inglezos** [comment] 2020-10-29 20:56
>
>Did you mean you want to do the following test?
>Please assume that the last date of actual records is 29Oct2020 here.
>Perform trend analysis
>Perform parameter estimation with the actual records of the last phase
>Simulate the number of cases from 30Oct2020 to 30Nov2020 with the fix parameter values estimated with the last phase
>Wait until 30Nov2020
>Compare actual number of cases from 30Oct2020 to 30Nov2020 and simulated number of cases from 30Oct2020 to 30Nov2020
>Calculate the difference of them
>
Yes, that was the test I meant. To take it one step further, if I wouldn't want to wait one month, what I was saying was to consider the last date of actual records as, for example, the 01Oct20 instead and run a simulation until today 29Oct20. Now, since I know the actual data from 01Oct20 - 29Oct20, I can compare the simulated with the actual. All I was asking was if all this is possible; and I think that it is, using the retrospective analysis, right?

>
>Because step 3 is an extrapolation, the score calculated in step 6 does not mean any types of accuracy.
>Details are here.
>The parameter set on 30Oct2020 may be the same as that on 29Oct2020 as you considered.
>However, that on 30Oct2020 may be different from that on 29Oct2020 because government responses and actions taken by people may change the parameter set.
>This means that, as well as errors of parameter estimation, government responses and actions can raise the difference of the number of cases between actual and simulated values.
>So, we cannot evaluate the accuracy of parameter estimation only with the comparison of actual values and simulated values using fixed parameter set.
>
Yes I understand that since government responses affect the parameters day-by-day, it is not possible to have a valid accuracy metric for that. Well then, how can we actually have some kind of accuracy for the estimated parameters / simulated cases?

**Comment by lisphilar** [comment] 2020-10-30 15:30
How about the following steps to evaluate models and the tools of CovsirPhy?
1. Check that we can estimate parameter values accurately with datasets that was created with user-defined parameters. This will be discussed in #290 
2. RMSLE scores of `Scenario.estimate()` are sufficiently small with actual data.

> To take it one step further, if I wouldn't want to wait one month, what I was saying was to consider as the last date of actual records a past day, for example, the 01Oct20 instead and run a simulation until today 29Oct20. Now, since I know the actual data from 01Oct20 - 29Oct20, I can compare the simulated cases with the actual cases immediately. All I was asking was if all this is possible; and I think that it is indeed, using the retrospective analysis, right?

Yes, but the first date of retrospective analysis should be selected carefully when you use this analysis for evaluation. The first date (you set as 01Oct2020) and the last date (you set as 29Oct2020) MUST be in the same phase because parameter values are changed phase-by-phase.

However, this idea is the same as RMSLE of `Scenario.estimate()` because RMSLE compares actual records and simulated records with estimated parameter values.
If we need to check the difference visually, `Scenario.estimate_accuracy(phase="1st")` (with phase name or "last") will ne used.

**Comment by lisphilar** [comment] 2020-10-31 09:17
Can we close this issue and move to #290, #282 and #291?

**Comment by Inglezos** [comment] 2020-10-31 17:37
Yes we can close it, thank you for your answers!

**Closed** 2020-11-01 03:03 UTC
Labels: question
