### ISSUE TITLE
[Fix] Scenario.records_diff() plots weird results for last values because of inadequate complement

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#450] opened 2020-12-19 14:46 UTC
## Summary
For some countries (example USA) `Scenario.records_diff()` plots weird results for last values for confirmed but especially recovered. I think this is caused due to some unupdated values at the end and for the recovered is caused by linear interpolation inside partial complement; there the linear method I guess produces evenly distributed values, which result in constant `diff()`. The problem is mostly for the visualization, seems kinda weird.
@lisphilar Do you have any ideas to improve this?

## Codes and outputs:
```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
# Scenario analysis
usa_scenario = cs.Scenario(jhu_data, population_data, "United States")
usa_scenario.records_diff()
```
This outputs plot:
<img width="686" alt="usa_records_diff" src="https://user-images.githubusercontent.com/36845191/102692168-4b9b8b80-421a-11eb-9099-993f9e12fc3c.png">

## Environment
- CovsirPhy version: 2.13.3-gamma
- Python version; 3.8
- Installation: pipenv
- System: WSL (Ubuntu)/Windows/Linux/Mac/Kaggle Notebook/Google Colaboratory

**Comment by Inglezos** [comment] 2020-12-19 14:47
This outputs plot:
<img width="686" alt="usa_records_diff" src="https://user-images.githubusercontent.com/36845191/102692121-d9c34200-4219-11eb-9463-8f81b85cf5ee.png">

**Comment by lisphilar** [comment] 2020-12-19 15:14
With the following results, the root cause may be in the order of complement methods in `._protocol()`.
`_monotonic(variable="Recovered")` was performed before `_recovered_partial()` was completed.

```Python
cs.Scenario(jhu_data, population_data, "USA", auto_complement=False).records().tail(15)
```
|     | Date                |   Infected |   Fatal |   Recovered |
|----:|:--------------------|-----------:|--------:|------------:|
| 300 | 2020-12-05 00:00:00 |    8792891 |  281222 |     5576026 |
| 301 | 2020-12-06 00:00:00 |    8924095 |  282344 |     5624444 |
| 302 | 2020-12-07 00:00:00 |    9021722 |  283763 |     5714557 |
| 303 | 2020-12-08 00:00:00 |    9166778 |  286283 |     5786915 |
| 304 | 2020-12-09 00:00:00 |    9283996 |  289347 |     5889896 |
| 305 | 2020-12-10 00:00:00 |    9412609 |  292267 |     5985047 |
| 306 | 2020-12-11 00:00:00 |    9493162 |  295550 |     6135314 |
| 307 | 2020-12-12 00:00:00 |    9598710 |  297904 |     6246605 |
| 308 | 2020-12-13 00:00:00 |    9736986 |  299293 |     6298082 |
| 309 | 2020-12-14 00:00:00 |    9928348 |  300777 |     6298082 |
| 310 | 2020-12-15 00:00:00 |   10124130 |  303761 |     6298082 |
| 311 | 2020-12-16 00:00:00 |   10367865 |  307429 |     6298082 |
| 312 | 2020-12-17 00:00:00 |   10600731 |  310774 |     6298082 |
| 313 | 2020-12-18 00:00:00 |   10847626 |  313588 |     6298082 |
| 314 | 2020-12-19 00:00:00 |   10847626 |  313588 |     6298082 |

```Python
cs.Scenario(jhu_data, population_data, "USA", auto_complement=True).records().tail(15)
```
|     | Date                |   Infected |   Fatal |   Recovered |
|----:|:--------------------|-----------:|--------:|------------:|
| 294 | 2020-12-05 00:00:00 |    8792891 |  281222 |     5576026 |
| 295 | 2020-12-06 00:00:00 |    8924095 |  282344 |     5624444 |
| 296 | 2020-12-07 00:00:00 |    9021722 |  283763 |     5714557 |
| 297 | 2020-12-08 00:00:00 |    9166778 |  286283 |     5786915 |
| 298 | 2020-12-09 00:00:00 |    9283996 |  289347 |     5889896 |
| 299 | 2020-12-10 00:00:00 |    9412609 |  292267 |     5985047 |
| 300 | 2020-12-11 00:00:00 |    9493162 |  295550 |     6135314 |
| 301 | 2020-12-12 00:00:00 |    9598710 |  297904 |     6246605 |
| 302 | 2020-12-13 00:00:00 |    9781109 |  299293 |     6253959 |
| 303 | 2020-12-14 00:00:00 |    9965117 |  300777 |     6261313 |
| 304 | 2020-12-15 00:00:00 |   10153545 |  303761 |     6268667 |
| 305 | 2020-12-16 00:00:00 |   10389927 |  307429 |     6276020 |
| 306 | 2020-12-17 00:00:00 |   10615439 |  310774 |     6283374 |
| 307 | 2020-12-18 00:00:00 |   10854980 |  313588 |     6290728 |
| 308 | 2020-12-19 00:00:00 |   10847626 |  313588 |     6298082 |

**Comment by Inglezos** [comment] 2020-12-19 16:30
Yes the complement is the cause, but it was applied correctly I think. The thing is that the linear interpolation probably generates evenly spaced values (at the end, replacing these 6298082), of which the diff is constant.

**Comment by lisphilar** [comment] 2020-12-19 16:56
What action is necessary?

**Comment by Inglezos** [comment] 2020-12-19 17:06
I'm not sure what we should do. Perhaps for these last values, upon `diff()`, we need a variation of linear interpolation which will keep the last value as mean value and create small +- differences around it to fill the other last values? I mean only for the diff dataset, not the original. The one produced by `usa_scenario.records().diff()` ->
![Uploading image.png…]()

**Comment by Inglezos** [comment] 2020-12-19 17:12
Alternatively, is there a way to create interpolation data for the original complement method but according to confirmed values? Not evenly spaced.

**Comment by lisphilar** [comment] 2020-12-19 17:20
Changes only for diff data may be confusing.

Do you mean time series prediction of recovered data with the time series of confirmation values? I don't remember the method name, but fbprophet will be useful.

**Comment by Inglezos** [comment] 2020-12-19 22:42
I mean that the interpolation should depend on the confirmed values, in order to generate corresponding values and not equally spaced. Is something like that possible?

**Comment by lisphilar** [comment] 2020-12-20 02:19
How does it depend on confirmed values?

**Comment by Inglezos** [comment] 2020-12-20 03:46
No it doesn't depend, just trying to find a way for the way not to be constant. We need to find a better way than linear interpolation. I don't know if this fbprophet package can solve this.

**Comment by lisphilar** [comment] 2020-12-20 15:18
It is better to use `pandas` methods for this purpose.
However, I could not find solutions with [pandas.DataFrame.fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) and [pandas.DataFrame.interpolate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html), without breaking monotonic increasing.

**Comment by Inglezos** [comment] 2020-12-22 02:29
I think I have found a solution, which is not very invasive, but yet effective. We can apply a kind of filling (bfill, ffill) for the ending duplicate values to the diff test values, not to test directly. In that way, when the last test values are the same and unupdated, the diff from zero will become the last non-zero value. This, over window rolling will give a smooth result, steady for the last days, which is what we want.

**Comment by Inglezos** [comment] 2020-12-22 02:50
I created pull request #457 for the two above problems.

**Comment by lisphilar** [comment] 2020-12-22 09:03
Many thanks for your pull request and I will read the codes from now.

Please confirm that this is an issue for `JHUData`, not `PCRData`.

I have a question.
Why this complement will be applied only for diff values?
Diff figure is supposed to use the same data as that we use in trend analysis and parameter estimation. I think this is a kind of complement. This is different from smoothing.

**Comment by Inglezos** [comment] 2020-12-22 14:31
Yes this concerns only the `Scenario.records_diff()` method for `JHUData`.

Yes you're right it is a kind of complement that has to be applied only and directly to the diff values, because we want to avoid the weird unchanged last values. The problem as I have explained is that for the last test values (not diff), the interpolation gives evenly spaced values, which have a constant diff, for some countries for the recovered especially way lower than the previous recovered diff. This leads to weird plot results.

Okay I agree, this is a solution I am not happy either, but I can't think of any other way :/

**Comment by lisphilar** [comment] 2020-12-22 15:04
I do not have tried, but can't we move `_records_diff_filling_ending` to complement hander class as a method?
.diff() and .cumsum() will be added to the first and last lines respectively.

**Comment by Inglezos** [comment] 2020-12-23 13:20
I reverted the change in order to be able to merge the other changes. We have to brainstorm on this.

**Comment by lisphilar** [comment] 2020-12-26 12:51
Please review my pull request #464.
This will update filling solution of `JHUDataComplementHandler._recovered_partial()` to update the filling solution of partial complement of recovered data. The number of daily new cases will be filled with forward method and coumulative values of daily values will be used as the complemented recovered data.
(Before: directly filled recovered values with forward solution of `.interpolate()`.)

For USA:
![Figure_rec](https://user-images.githubusercontent.com/7270139/103151769-68a8ff00-47c4-11eb-91e3-11856e4a7855.png)
![Figure_diff](https://user-images.githubusercontent.com/7270139/103151771-6a72c280-47c4-11eb-896f-d4d40860688d.png)

**Comment by Inglezos** [comment] 2020-12-26 16:04
Great, I have approved these changes!! So we transfer this diff specific fill to general partial complement, I agree.

**Comment by lisphilar** [comment] 2020-12-27 02:49
Thank you for confirmation, it was merged.

**Comment by Inglezos** [comment] 2020-12-27 03:34
Can you run again the analysis for USA and Greece? I get some weird plots and I think something is going on with the complement change. I mean this code:
```
import covsirphy as cs

usa_scenario = cs.Scenario(jhu_data, population_data, "United States")
usa_scenario.records_diff()
usa_scenario.records()
pcr_data.positive_rate("United States")
_ = usa_scenario.trend()

gre_scenario = cs.Scenario(jhu_data, population_data, "Greece")
gre_scenario.records_diff()
gre_scenario.records()
pcr_data.positive_rate("Greece")
_ = gre_scenario.trend()
```

They are very different with recent previous executions.

**Comment by lisphilar** [comment] 2020-12-27 05:52
Should we revert #464?

For USA,
```Python
import covsirphy as cs
data_loader = cs.DataLoader()
jhu_data = data_loader.jhu()
population_data = data_loader.population()
usa_scenario = cs.Scenario(jhu_data, population_data, "United States")
usa_scenario.records()
```
![Figure_1](https://user-images.githubusercontent.com/7270139/103164801-09de9680-4853-11eb-9dad-be16702a4f53.png)

**Comment by lisphilar** [comment] 2020-12-27 09:01
When line 61 `(self.R, self._recovered_partial_ending, 3),` is removed, the figure shows expected outputs.
Is it  necessary to keep `self._recovered_partial_ending()` method in the current version?
![Figure_usa](https://user-images.githubusercontent.com/7270139/103167326-9302c700-486d-11eb-9409-f28f354a51eb.png)
![Figure_greece](https://user-images.githubusercontent.com/7270139/103167328-95fdb780-486d-11eb-9468-55d8362a15b4.png)

**Comment by Inglezos** [comment] 2020-12-27 11:20
1. First we should apply some kind of constraint to `df[self.R] = first_value + diff_series.cumsum()` in order to be `<= df[self.C] - df[self.F]`.
2. Then we should revise the new partial complement method because for example Greece, the previous results were far more correct:
![gre_records](https://user-images.githubusercontent.com/36845191/103169443-4bb41080-4844-11eb-9919-a6f13cb50069.jpg)
But now the generated recovered max (4636) is far lower than the actual recovered (at least the reported, which are 93764). This is without the `_recovered_partial_ending`.
3. We have to keep `_recovered_partial_ending` but after that apply `_recovered_sort`, right before `_recovered_partial`.
4. For Greece, the new solution is wrong, since many values are missing (only 22 unique values) and to keep the previous diff (which for Greece for some reason is only 17 always), is not representative at all and yields wrong results. If we keep the current solution, then we must discern such cases (unique values percentage like in pcr check) and apply interpolation instead. If you debug manually the Greece scenario (set breakpoint in `first_value = df.loc[df.index[0], self.R]` you will see the values behavior.

**Comment by lisphilar** [comment] 2020-12-27 14:53
In my local environment, I changed line 278-281 of jhu_complement.py as follows. (This means reverting #464.)
Before:
```Python
        # Complement in-between values
        first_value = df.loc[df.index[0], self.R]
        df.loc[df.duplicated([self.R], keep="first"), self.R] = None
        diff_series = df[self.R].diff().ffill().fillna(0)
        df[self.R] = first_value + diff_series.cumsum()
```
After:
```Python
        # Complement in-between values
        df.loc[df.duplicated([self.R], keep="last"), self.R] = None
        df[self.R].interpolate(
            method="linear", inplace=True, limit_direction="both")
        df[self.R] = df[self.R].fillna(method="bfill")
```

However, figures were not changed. The change does not impact on this new un-expected behavior.
![Figure_1](https://user-images.githubusercontent.com/7270139/103173457-5ef3ca00-489e-11eb-99c0-1a3df8d3fb8a.png)

**Comment by Inglezos** [comment] 2020-12-27 15:03
This is almost correct. If we revert to the previous code, this is correct. The actual recovered data from JHU show a sudden spike from 23k to 93.7k

**Comment by Inglezos** [comment] 2020-12-27 15:05
So what we have to further discuss about such cases with few unique values, is if we should apply a more specific complement for these sparse in between unupdated values, in order to increase more smoothly or not.

**Comment by Inglezos** [comment] 2020-12-27 15:06
All this is if we revert the change. With the current code the Greece analysis is problematic regarding the recovered.

**Comment by Inglezos** [comment] 2020-12-27 15:08
One quick solution would be to count unique values (just like in pcr) and if there exist less than 50% (or 10% or a threshold) of the total records, then invalidate them completely and produce full complementary recovered data. But I think that since we have at least some few valid data, it would be better to use them however we can instead of choosing the easy path of full complement, and that's the reason why I am trying to think of a handling mechanism for such cases.

**Comment by lisphilar** [comment] 2020-12-27 15:09
I created pull request #468 to revert the codes.

**Comment by lisphilar** [comment] 2020-12-27 15:11
After merging #468, please try to update the codes for the solution.

**Comment by Inglezos** [comment] 2020-12-28 04:40
What solution do we agree on though?

**Comment by lisphilar** [comment] 2020-12-28 05:35
When we have small numver of records, we try to use the records as the fixed points rather than applying full complement.

As an example, we may use
1. curve fitting with exponential function or,
2. spline complement with sorting.

**Comment by Inglezos** [comment] 2020-12-28 10:25
This is currently implemented for any case nevertheless, but with linear interpolation. So you mean change linear to spline method instead plus sorting? Or only for the few unique case? I mean is it now necessary (after revert) to discern the few unique case or just apply spline altogether for every case generally, in order to smooth such rapid changes? Which one is more preferable?

**Comment by lisphilar** [comment] 2020-12-28 11:16
I said "When we have small number of records, we try to use the records as the fixed points rather than applying full complement."

It seems I'm misunderstanding the discussion, and please try this issue with codes?

**Comment by Inglezos** [comment] 2020-12-28 11:41
>When we have small number of records, we try to use the records as the fixed points rather than applying full complement
>
But that's what we are currently doing. In such cases, we use these sparse points with linear interpolation. Are you suggesting to use spline interpolation instead?

**Comment by lisphilar** [comment] 2020-12-28 12:26
exponetial curve fitting and sline interpolation with sorting may be useful, but I do not know the effectivity of these solutions.

**Comment by Inglezos** [comment] 2020-12-30 16:02
Created pull request #472.
Improved `_recovered_partial()` and `_recovered_partial_ending()`. For overcoming the constant ending diff values upon complementing, these ending diff values were interpolated in order to create some kind of variance.

**Comment by lisphilar** [comment] 2020-12-31 04:22
Thank you for your pull request!!!
I added some comments.

**Comment by lisphilar** [comment] 2021-01-03 08:44
With #472, this bug was fixed. Thank you!

USA diff records:
![Figure_usa](https://user-images.githubusercontent.com/7270139/103474851-2cd8ef80-4deb-11eb-9b97-e8f6b323c622.png)

Greece records:
![Figure_Greece_records](https://user-images.githubusercontent.com/7270139/103474854-2fd3e000-4deb-11eb-9662-648306aa0469.png)

**Closed by lisphilar** 2021-01-03 08:44 UTC
Labels: bug
