### ISSUE TITLE
Handling Netherlands missing recovered data

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#334] opened 2020-11-15 00:23 UTC
## Summary
We cannot apply any kind of analysis for Netherlands because the JHU CSSE reports 0 recovered cases data.
The root cause for this is that it seems the country itself does not report any recovered cases data. See also here:
https://github.com/CSSEGISandData/COVID-19/issues/2591
What can we do in this case to overcome this? Could we generate completely such data, in the same logic with the complementary method?

**Comment by lisphilar** [comment] 2020-11-15 02:56
Yes, the root cause is un-registered recovered data.
If we have linelist of case reports discussed in #281 , we may calculate the number of confirmed/recovered/fatal cases with it. `DataLoader` class and `JHUdata.replace()` will be used.

**Comment by lisphilar** [comment] 2020-11-19 16:05
Dear @Inglezos ,
Kindly comment on my solution with time-lag of confirmation and closing.
https://gist.github.com/lisphilar/9c5f0a96c88a27be0c3e085ced89a2b1

**Comment by Inglezos** [comment] 2020-11-19 18:10
Could you describe a little more what you are attempting to do in this solution? I ran this code by myself and I get the same results with you. This method will be integrated to the cleanup of the dataset?

**Comment by lisphilar** [comment] 2020-11-20 10:53
My solution is
1. Calculate total number of cases (line 5 in the gist notebook of the previous comment)
2. Calculate the number of closed (=Recovered + Fatal) cases (line 6)
3. Calculate how many days have passed since the number of **confirmed** cases reach `N_i` cases (i = 1, 2, 3,....) (line 8)
4. Calculate how many days have passed since the number of **closed** cases reach `N_i` cases (i = 1, 2, 3,....) (line 8)
5. Calculate the difference of 3. and 4. for each `N_i` (line 8)
6. Calculate `mode value of the difference` (I selected mode, not mean, not median, because bimodal) (line 11)
7. Assume that cases in Netherlands get outcome at `mode value of the difference`-th day from comfirmation date
8. Estimate the number of recovered cases in Netherlands as `Confirmed.shift(mode value of the difference) - Fatal` (line 15)
9. Calculate Infected as `Confirmed - Recovered - Fatal` (line 15)
10. Complement finished

I have just tried on the gist notebook yesterday, and I will try to create a pull request to update `JHUData` and `Scenario.complement()` today.

**Comment by lisphilar** [comment] 2020-11-20 16:08
I created pull request #347 .
Kindly review it, if you have time.

**Comment by Inglezos** [comment] 2020-11-21 01:21
I have reviewed your changes and I approved them, thank you very much!
I have one question, what happens if the mode value is large and we cannot know the confirmed and fatal cases?
For example if the mode value is 20 and we want to complement last week's recovered data, we simply cannot since we don't know yet the confirmed and fatal cases for the future 14th day from today. I think there should be added a check/case/handling method inside `_complement_recovered_full()`, at line:
```
        # Estimate recovered records
        shifted = df[self.C].shift(periods=self._closing_period, freq="D")
```
in order to ensure that the shift does not exceed the length of the total records of `df`

**Comment by lisphilar** [comment] 2020-11-21 07:12
Thank you for reviewing #347  and I merged it!

In your example, today's recovered data will be calculated with confirmed/fatal values 20 days **ago**, not future values. This is because "Fatal + Recovered" is always smaller than "Confirmed" and "Fatal + Recovered" reach 1000 cases 20 days later if mode value is 20 days.

When `df[self.C].to_dict()` is `{"01Oct2020": 1000, "02Oct2020": 1010,...}` and `self._closing_period=20`,
```Python
shifted = df[self.C].shift(periods=self._closing_period, freq="D")
```
creates `shifted.to_dict()={"21Oct2020: 1000, "02Oct2020": 1010,...}`.

Then, `shifted.fillna(0).astype(np.int64)` is the same as `{"01Oct2020": 0, "02Oct2020": 0,..., "21Oct2020": 1000, "22Oct2020": 1010,...}` with `.to_dict()`.

**Comment by Inglezos** [comment] 2020-11-22 03:46
I noticed that some first recovered cases are negative and are excluded with:
`# Select records where Recovered > 0`
`df = df.loc[df[self.R] > 0, :]`
inside `subset_complement()`
This leads to have as first record date the `17April2020` for Netherlands, which means that the first 1.5 month of data are ignored because of the negative recovered generated data. Is this normal?

**Comment by lisphilar** [comment] 2020-11-22 09:40
I updated `JHUData._complement_recovered_full()` with #350 to replace negative/NA values to 0.
Before:
```Python
shifted = df[self.C].shift(periods=self._closing_period, freq="D")
df[self.R] = shifted.fillna(0).astype(np.int64) - df[self.F]
```
After:
```Python
shifted = df[self.C].shift(periods=self._closing_period, freq="D")
df[self.R] = (shifted - df[self.F]).fillna(0).astype(np.int64)
df.loc[df[self.R] < 0, self.R] = 0
```

Records with `Recovered = 0` should be removed from dataset when we analyse it because un-changed number of cases decreases accuracy of estimation. ODE-derived models are not good when the number of cases is very small.

**Comment by lisphilar** [comment] 2020-11-22 15:25
I updated codes with #353 .
Before:
```Python
shifted = df[self.C].shift(periods=self._closing_period, freq="D")
df[self.R] = (shifted - df[self.F]).fillna(0).astype(np.int64)
df.loc[df[self.R] < 0, self.R] = 0
```
After:
```Python
shifted = df[self.C].shift(periods=self._closing_period, freq="D")
df[self.R] = shifted - df[self.F]
df.loc[df[self.R] < 0, self.R] = None
# Fill in NA values with Extrapolated values
df[self.R].interpolate(method="spline", order=1, inplace=True)
df[self.R] = df[self.R].fillna(0).astype(np.int64)
# Ensure Recovered values show monotonic increasing
df = self._complement_non_monotonic(
df.reset_index(), [self.R]).set_index(self.DATE)
```

`JHUData._complement_non_monotonic()` was created with #351 to ensure that the selected columns show monotonic increasing.

**Comment by lisphilar** [comment] 2020-11-24 13:09
Can we close this issue?

**Comment by Inglezos** [comment] 2020-11-24 22:40
I think so, yes we can close this. If something comes up we can create a new issue.

**Closed** 2020-11-25 13:51 UTC
Labels: enhancement

**Comment by rebeccadavidsson** [comment] 2021-02-28 14:46
From the [notebook](https://gist.github.com/lisphilar/9c5f0a96c88a27be0c3e085ced89a2b1) it seems like the number of recovereds is calculated by summing the fatalities and recovereds `df["Closed = Recovered + Fatal"]` , is that indeed the case for countries with missing recovered-data?

**Comment by lisphilar** [comment] 2021-02-28 16:58
This an old issue for that. The latest strategy is documented here.
https://lisphilar.github.io/covid19-sir/

**Comment by lisphilar** [comment] 2021-02-28 17:00
This calculation system was updated with #420 for example.
