### ISSUE TITLE
Questions about tau variable interpretation

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#392] opened 2020-12-09 10:40 UTC
## Summary of questions
1. What is exactly the definition of tau = 1440 min? What does it represent, what is the physical interpretation?
Does this mean that 1440 discrete solutions of the ODE model correspond to one day interval?

2. When we say for example that sigma = 0.075, does this mean that 0.075 people get recovered per minute? So in a day the recovered will be 1440 x 0.075 = 108? Or that means that 0.075 is per day instead (since time unit is 1440 min = 1 day) and one recovered will be in 1/0.075 = 13 days?

3. You had said in an older comment that "In Italy, tau was calculated as 434 [min] in scenario analysis version 155." What does that mean? That the time step for that analysis was smaller and thus it was cases per ~7.2 hours? Why not keep a constant tau throughout the analysis, why consider it as a variable/parameter?

**Comment by lisphilar** [comment] 2020-12-09 16:05
Let's discuss the issues one by one. Many question marks are confusing and makes it difficult to get main points.

`tau` is not always equal to 1440. `tau` is used to convert actual time (with unit [min]) to time steps (without units). This convertion enables us to use actual dataset with ODE models. No reference, but it is useful because removal of units simplify parameter estimation.

Please refer to "dimensionless quantity".

**Comment by Inglezos** [comment] 2020-12-09 18:28
I regrouped my questions, including your previous answers:

1.
> tau is not always equal to 1440.
>
Okay, so tau is generally considered as a variable/parameter and not standard fixed to 1440. 
The estimator determines tau value? The constraint is applied by the estimator that grounds tau values and defines its value?

2. In the example data how come it is fixed 1440? Because we deliberately set the data in that way that tau would be always 1440?

3.
> tau is used to convert actual time (with unit [min])
>
Why we assume that actual time is in [min] and not in [sec] or [day] ?

4. The refresh rate of the original data source, from JHU is per day. If I understand correctly, actual time can be whatever unit, as long as tau has the same inverse time unit in order to produce the optimized time steps in the dimensionless system?

5. When we say for example that sigma = 0.075, does this mean that 0.075 people get recovered per minute?
So in a day the recovered will be 1440 x 0.075 = 108? 
Or that means that 0.075 is per day instead and one recovered will be in 1/0.075 = 13 days?

**Comment by lisphilar** [comment] 2020-12-11 13:45
> The estimator determines tau value?
The estimator determines tau value when not specified.

Default behaviour of `Scenario.estimate()`: 
- With the records of the last phases. the estimator determines tau value.
- In the all phases except for the last phases, the determined tau value will be used. Tau value will not be updated.

> The constraint is applied by the estimator that grounds tau values and defines its value?

Tau value is a divisor of 1440 [min] (= 1 [day]) in CovsirPhy with `Terms.ensure_tau()`. This constraint simplify `.simulate()` method, but do not have scientific reason.

> In the example data how come it is fixed 1440? Because we deliberately set the data in that way that tau would be always 1440?

This is just a example. We can change the tau value of the example data, like `example_data = ExampleData(tau=360)`.


> Why we assume that actual time is in [min] and not in [sec] or [day] ? The refresh rate of the original data source, from JHU is per day. If I understand correctly, actual time can be whatever unit, as long as tau has the same inverse time unit in order to produce the optimized time steps in the dimensionless system?

We do not know the exact time scale of infection.
Because the refresh rate is per day, the unit of tau value should be equal to or under 1 day. More than 1 day cannot be accepted, but tau value will 1 day or 2 days or 3 days if [day] is selected.
[sec] is too small because 1440 * 60 has too many divisors and makes estimation inefficient.


> When we say for example that sigma = 0.075, does this mean that 0.075 people get recovered per minute? So in a day the recovered will be 1440 x 0.075 = 108? Or that means that 0.075 is per day instead and one recovered will be in 1/0.075 = 13 days?

Sigma is a non-dimentional value. Dimentionl value of sigma is `1/gamma` [day]. This will be calculated as `tau/ 24 / 60 / sigma` and `1/gamma` [day] means the number of days for the confirmed cases to recover.

**Comment by lisphilar** [comment] 2020-12-11 13:47
Please update `docs/markdown/TERM.md` to document "tau value" and so on in https://lisphilar.github.io/covid19-sir/TERM.html

**Comment by lisphilar** [comment] 2020-12-11 13:49
Note that `gamma` [1/time] is the recovery rate in SIR-derived models.

**Comment by Inglezos** [comment] 2020-12-11 14:04
1. > With the records of the last phases. the estimator determines tau value.
    > In the all phases except for the last phases, the determined tau value will be used. Tau value will not be updated.
    >
So tau is determined by the estimator only during the last phase? And then uses that tau value as it is for all the previous phases as well?

2. So when tau is estimated/set to be for example 360 instead of 1440, than would mean the analysis is more effective if we study the records per 6 hours (since 360/1440 = 1/4) and not as a whole day?

3. > More than 1 day cannot be accepted, but tau value will 1 day or 2 days or 3 days if [day] is selected.
>
So tau is strictly <= 1. Nevertheless, you mean we could set tau > 1 but that would lead to bad results?

4. > Sigma is a non-dimentional value. Dimentionl value of sigma is 1/gamma [day]. This will be calculated as tau/ 24 / 60 / sigma and 1/gamma [day] means the number of days for the confirmed cases to recover.
>
For some countries for example, I see that 1/gamma is very high, i.e. For Italy across all phases is ~[30-80]. That means that the model estimated that for Italy, at times, the recovery period was even 80 days? (!)

**Comment by lisphilar** [comment] 2020-12-11 15:37
> 1. So tau is determined by the estimator only during the last phase? And then uses that tau value as it is for all the previous phases as well?

Yes.This is controlled by instance variable `Scenario.tau`.

> 2. So when tau is estimated/set to be for example 360 instead of 1440, than would mean the analysis is more effective if we study the records per 6 hours (since 360/1440 = 1/4) and not as a whole day?

Yes, I think. Estimation and simulation is based on this idea.

> 3. So tau is strictly <= 1. Nevertheless, you mean we could set tau > 1 but that would lead to bad results?

When tau = 2 [days] and actual data is [100 (1st date), 110 (2nd date), 120 (3rd date), 130 (4th date)], dimension-free dataset will be [100, 120]. Many records will be ignored. This is not a good choice.


> 4. 1/gamma [day] means the number of days for the confirmed cases to recover.

Sorry, this is under the assumption that all/most of cases take the same medical history to recover. Please refer to sites which explain the simplet SIR model.

**Comment by Inglezos** [comment] 2020-12-12 16:51
> Sorry, this is under the assumption that all/most of cases take the same medical history to recover
>
So this means that 1/gamma actually won't match the real recovery rate we see in the actual cases? Is this wrong?
Then how come the estimated recovery cases are pretty close to the actual cases indeed?

**Comment by lisphilar** [comment] 2020-12-13 07:56
> So this means that 1/gamma actually won't match the real recovery rate we see in the actual cases?

Yes.

> Then how come the estimated recovery cases are pretty close to the actual cases indeed?

I do not have ideas, but comparison of 1/gamma and recovery period calculated with linelist in each country will make good suggestions.

**Comment by lisphilar** [comment] 2020-12-13 13:33
Please summarize your undestanding and create a pull request to add description of tau value in docs/markdown/TERM.md file. This will be shown in https://lisphilar.github.io/covid19-sir/TERM.html

**Comment by Inglezos** [comment] 2020-12-13 15:11
Please review my description of tau definition.

**Comment by lisphilar** [comment] 2020-12-13 15:33
Thank you for update. Your pull request was merged.
Will we continue the discussion regarding the relationship of 1/gamma and recovery period in a new issue?

**Comment by Inglezos** [comment] 2020-12-13 15:38
> comparison of 1/gamma and recovery period calculated with linelist in each country will make good suggestions.
>
I don't think we have enough linelist data generally, let alone for multiple countries.
If you have some time yes, create the respective issue, but this is of lower priority I think.

**Comment by lisphilar** [comment] 2020-12-13 15:55
Yes, this is of low priority. I created a discussion forum with "Ideas" label in #416, not a issue page.
Discussion forum (https://github.com/lisphilar/covid19-sir/discussions) was created for low priority tasks. This is a beta-feature of GItHub.

**Closed by lisphilar** 2020-12-13 15:55 UTC
Labels: documentation, question
