### ISSUE TITLE
[Question] dataset for India is needed 

### ISSUE THREAD

**Issue by shubhamias12** [lisphilar/covid19-sir#726] opened 2021-04-19 14:55 UTC

**Comment by lisphilar** [comment] 2021-04-20 09:43
Could you provide the details?

**Comment by shubhamias12** [comment] 2021-04-20 09:59
I wanted to use the model for the city-wise analysis of covid cases in India, when we select the country it is only picking the data for Japan. How I can use the data from the other countries. I am working on a college project.

**Comment by lisphilar** [comment] 2021-04-20 10:22
Thank you.
Could you share the codes?

If you used the script in README, you can change country and province when creating `Scenario` instance.
```Python
snl = cs.Scenario(country="India", province=”Orissa”)
```

Actually, city-wise data is not collected by CovsirPhy at this time. This could be a new enhancement.

**Comment by shubhamias12** [comment] 2021-04-20 10:46
OK thanks for replying and if I found again issue I let you know thanks

**Comment by shubhamias12** [comment] 2021-04-20 11:04
from covsirphy.ode.ode_handler import ODEHandler
ModuleNotFoundError: No module named 'covsirphy.ode.ode_handler'
this error coming and i am not able to solve this error can you help

**Comment by lisphilar** [comment] 2021-04-20 16:04
Could you share the URL which have `parser.add_argument(...)` codes? This repository does not provide command line tools now.

For `ModuleNotFoundError`, please also share the all codes? Sorry, I could not reproduced the error.

**Comment by shubhamias12** [comment] 2021-04-20 16:34
Its ok. Actually I was running the code on visual code and their I was getting the error but when I running SI model on Google cobel i did not get the error in snl demo example . Anyway thanks for commenting and helping

**Comment by lisphilar** [comment] 2021-04-20 16:48
Thank you.
I will close this issue and you can create new issues if you have any troubles. At the next time, when creating issues in this repository, please edit the issue template to add the details.

**Closed by lisphilar** 2021-04-20 16:48 UTC
Labels: New data loader, enhancement
