### ISSUE TITLE
Full compliment initial condition (problem with France)

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#421] opened 2020-12-16 00:49 UTC
## Summary
France has two issues:
The first one, as the code currently is, is that during the Scenario call, it throws a:
```
UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
```
which means that a spline action failed during the complement.

The second and major issue is the fact that the recovered data for France seem okay, even though they are kinda much lower than confirmed. I mean it would be more correct to let them be as they are. The condition that indicates wrongly the full compliment is in `_recovered_full()` the `r > (c - f) * 0.1`.

Since we compare right after that how close r is to c, using `sel_2`, I think it would be better to just remove it.

**Comment by lisphilar** [comment] 2020-12-16 09:53
Please use the issue template for bugs with codes.

**Comment by lisphilar** [comment] 2020-12-16 13:02
For the first one, why extrapolation with spline failed?

**Comment by lisphilar** [comment] 2020-12-16 13:59
I created pull request #425 to supress `UserWarning` in `JHUDataComplementHandler._monotonic()` and fix `JHUDataComplementHandler._recovered_sort()`.

For the second one, do you mean `if r > self.max_ignored and r > (c - f) * 0.1:` should be removed? If yes, I agree and removed it with the pull request.

**Comment by Inglezos** [comment] 2020-12-16 14:22
Yes that is what I meant. I approved these changes. I don't know why spline failed, perhaps it could not find suitable line to fit.

**Comment by lisphilar** [comment] 2020-12-16 14:23
Thank you.
However, I have just found that full complement was not performed for Francce with this change.
![fra_records](https://user-images.githubusercontent.com/7270139/102360664-a6a06900-3ff5-11eb-9ce6-0e1d39d58cfd.jpg)

**Comment by Inglezos** [comment] 2020-12-16 14:24
I think that for France we have original valid recovered data, why full compliment is needed?

**Comment by lisphilar** [comment] 2020-12-16 14:27
With the figure, I thought Recovered << Confirmed. I will check another source.

**Comment by lisphilar** [comment] 2020-12-16 14:34
No discreapancy. We may nedc tou use 179087 at this time.

**Comment by Inglezos** [comment] 2020-12-16 14:38
Yes the recovered data as they are provided by JHU CSSE are way lower than the confirmed, but they seem valid. I think for this case it would be an exaggeration to fully compliment them, since they are not missing or totally invalid.

**Comment by lisphilar** [comment] 2020-12-16 15:01
Thank you for confirmation. The pull request was merged and I will close this issue.
Because this is a fatal error for France, new minor version 2.13.1 will be released.

**Closed by lisphilar** 2020-12-16 15:01 UTC
Labels: bug
