### ISSUE TITLE
[Discuss] Plots of countries with low infected and high recovered data

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#423] opened 2020-12-16 01:12 UTC
## Summary
I noticed that for the majority of the countries, the recovered data are increased but there is a weird lower infected plot line. It is kind of weird to see that for example there are few infected, but we have a high recovered plot and I wondered what is the physical interpretation of that? That someone who gets confirmed almost immediately gets recovered?

Are we doing something wrong? Is it the complementary method we apply? How can this be reworked? Is this actually a problem?

I mean the following plots for example:
![jpn_records](https://user-images.githubusercontent.com/36845191/102291599-23770880-3f4c-11eb-9516-5acba11947c0.jpg)
![chn_records](https://user-images.githubusercontent.com/36845191/102291602-2671f900-3f4c-11eb-96f8-0f860aaf0ad7.jpg)
![ind_records](https://user-images.githubusercontent.com/36845191/102291611-2a058000-3f4c-11eb-8c42-a178c5bbbbb6.jpg)
![brz_records](https://user-images.githubusercontent.com/36845191/102291631-3558ab80-3f4c-11eb-9ffa-825165937a8a.jpg)
![rus_records](https://user-images.githubusercontent.com/36845191/102291638-3984c900-3f4c-11eb-9e69-d3e06527c3f4.jpg)
![spn_records](https://user-images.githubusercontent.com/36845191/102291646-3ee21380-3f4c-11eb-90f4-9e2b7bb14de8.jpg)
![fra_records](https://user-images.githubusercontent.com/36845191/102291658-42759a80-3f4c-11eb-9113-631fa451fb44.jpg)
![uk_records](https://user-images.githubusercontent.com/36845191/102291670-45708b00-3f4c-11eb-87ea-6dd5ff1f9429.jpg)
![deu_records](https://user-images.githubusercontent.com/36845191/102291675-49041200-3f4c-11eb-9a3f-a0c64c7f9af8.jpg)
![nld_records](https://user-images.githubusercontent.com/36845191/102291680-4c979900-3f4c-11eb-8e12-e822b712689e.jpg)

**Comment by Inglezos** [comment] 2020-12-16 01:44
Do you think that we should have used exponential distribution or something else instead of a simple shift of C to produce R, for the full complements?

**Comment by lisphilar** [comment] 2020-12-16 09:38
1. Japan, India, Russia
I could not find any issues when I compared confirmed data and recovered data.
Please refer to https://gist.github.com/lisphilar/5bb6feea7498cadb120567b249804fd5

2. Brazil
Pratial complement of recovered data is ineffective.
This will be discussed in #424.

2. China, Spain, France, UK, Germany, Netherlands
We do not know the actual values of recovered data. Fully complemented.

**Comment by Inglezos** [comment] 2020-12-16 14:57
What I don't understand seeing these plots is how can the infected be that low, while the recovered are so high. I mean, when I try to read these plot and interpret them, for example in Japan, up until October, I can see that there are two peaks if infected at around <20.000. So I would expect that the plot of recoveries would be as high as 40.000 or 50.000. How can it reach 150.000 for example? How is this explained? Similarly for all the other plots above.

**Comment by lisphilar** [comment] 2020-12-16 15:34
In Japan, we experienced two waves and we are in third wave. In the first wave (Apr - May), recovery period was too long because collapse of the medical care system occurred and no medicines were found.

However, in the second wave (Jul - Oct), recovery period appears short because we have some effective medicines (not approved, in clinical study), yonger people (people un-associated to sever diseases) were infected.

In the third wave (Nov - ), older people tend to be infected and we are facing with medical collapse at this time...

This can be discussed with the history of sigma values (recovery rates) calculated with `Scenario.history_rate("sigma")`.
Please refer to the next figure.
Sigma values: the first wave < the second wave > the third wave

![jpn_history_sigma](https://user-images.githubusercontent.com/7270139/102369418-40b8df00-3fff-11eb-9117-6dcaf35c82de.jpg)

**Comment by Inglezos** [comment] 2020-12-16 15:45
No I don't mean this. I mean that the infected peaks, if they are added, shall give the peak recoveries (this is from my intuition):
![jpn_records_temp](https://user-images.githubusercontent.com/36845191/102371065-77bece80-3fc6-11eb-84f6-26ac5b359641.jpg)

**Comment by Inglezos** [comment] 2020-12-16 15:47
My intuition says that all the recoveries, must first pass from infections stage, so they must be somehow represented in Infected plot. How can recoveries be that high, when we have too few infections compared? Where all the rest recoveries come from?
Don't I understand something or do I read the plot incorrectly?

**Comment by lisphilar** [comment] 2020-12-16 15:48
I think this occurs when infection speed << recovery speed.

**Comment by Inglezos** [comment] 2020-12-16 15:58
So this means that a high percent of the daily confirmed as soon as they are added to infected, a large amount of infected moves to recovered and so the accumulative recovered plot increases, while the infections flux remains constant? That's why we don't see large increases in infections because soon the recoveries kick in and subtract infections?

**Comment by Inglezos** [comment] 2020-12-16 16:03
So this behavior is correct and can happen when recovery speed > infection speed ?
Is it normal that infection speed is way lower than recovery speed?

**Comment by lisphilar** [comment] 2020-12-17 14:48
Yes, I think.
At this time, we do not follw the flow of cases. Agent-based model discussed in #396 will be a useful tool to understand this flow. Please refer to YuTube video https://www.youtube.com/watch?v=gxAaO2rsdIs

**Comment by Inglezos** [comment] 2020-12-17 15:18
What do you mean the flow of cases? The compartments we use aren't supposed to indicate such population flow from one to another?

**Comment by lisphilar** [comment] 2020-12-17 15:23
I meant that we do not know when a case (confirmed on 01Nov2020 as an example) recovered.

**Comment by lisphilar** [comment] 2020-12-19 14:04
Can we close this discussion?

**Comment by Inglezos** [comment] 2020-12-19 14:10
I think yes!

**Comment by lisphilar** [comment] 2020-12-19 14:20
Thank you!

**Closed by lisphilar** 2020-12-19 14:20 UTC
Labels: bug, question
