### ISSUE TITLE
Handling irregular JHU infected/recovered data for Brazil and Germany

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#339] opened 2020-11-15 21:01 UTC
## Summary
1) For Brazil, until 06 March 2020, the JHU data are very wrong. In specific, for example:
![image](https://user-images.githubusercontent.com/36845191/99196657-75ced900-2796-11eb-82a5-8eb87370767d.png)
There are negative numbers for cases data. Also the records begin before 22Jan20, which date is considered the onset of the pandemic. This leads the `snl.estimate(cs.SIRF)` for Brazil to throw error: `ValueError: Mean Squared Logarithmic Error cannot be used when targets contain negative values.` No analysis can be done for Brazil.
[UPDATE:] This error seems to happen because the "Espirito Santo" province is recognized upon `_subset_by_province()` call, and contains these erroneous data.

2) Also I noticed that for Germany the records begin from January 3rd. This is again impossible, considering that the first cases appeared in China on January 22!

- In general, we must apply some preprocessing to the JHU source data after `DataLoader()`.
- We must put a lower limit for the first cases date and use China's onset date. We could even sum all the cases prior to 22Jan and use this sum as the first cases record.
- We must check for and handle negative cases values in the source data. The easiest way to solve this would be to ignore such data completely.

**Comment by lisphilar** [comment] 2020-11-16 14:43
I found that `Confirmed < Fatal + Recovered` from 01Jan2020 to 05Mar2020 with cleaned data of Brazil, not with raw data.
https://gist.github.com/lisphilar/2625e2e8b86ec6ba40a8fe60dfd425b2

In `cs.JHUData._cleaning()` method, I used
```Python
df = df.interpolate(limit_direction="both")
df[self.CI] = df[self.C] - df[self.F] - df[self.R]
```
`limit_direction="both"` may be the cause. I will try to fix it.

**Comment by lisphilar** [comment] 2020-11-16 15:12
I'm sorry. Change of filling method is necessary, but this is no the cause.
As you mentioned, `JHUData.subset()` should be re-written not to use `CleaningBase._subset_by_province()`. This method was created to use both of COVID-19 Data Hub and Kaggle dataset. We can remove codes for the Kaggle dataset.

**Comment by lisphilar** [comment] 2020-11-16 15:23
Error handling should be added, but the simplest codes of the top of `JHUData.subset()` are
```Python
country = self.iso3_to_country(country)
df = self._cleaned_df.copy()
df = df.lo[(df[self.COUNTRY] == country, df[self.PROVINCE] == province)]
# + handling start_date, end_date
```

**Comment by lisphilar** [comment] 2020-11-17 16:36
Brazil:
I updated dataset classes, including `JHUData`, with pull request # .
Please confirm that negative values were revised.

Germany:
The first case in Germany was confirmed on 27Jan2020, according to Wikipedia. (We need further investigation, but the confirmation date of the first COVID-19 case is not 22Jan2020. On 16Jan2020, Japanese government annouced that the first Japanese case was confirmed. The first date when JHU team started to collect data may be 22Jan2020. )

I did not have time today, but we need to check the number of cases in Germany with https://en.wikipedia.org/wiki/Statistics_of_the_COVID-19_pandemic_in_Germany

Then, we will notify COVID-19 Data Hub team with a new promary data source or create data loader method in CovsirPhy to use the new primary data source.

**Comment by lisphilar** [comment] 2020-11-25 13:51
Please confirm issue for Brazil was solved.
For Germany, how do you think about my previsous comment? Do you have any ideas to find new primary data source?

**Comment by Inglezos** [comment] 2020-11-25 18:10
Yes the Brazil issue is resolved.
For Germany the only data source I could find is interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit, but it seems there is no API/csv records.

**Comment by lisphilar** [comment] 2020-11-26 14:34
> Generally, how much RMSLE score is okay and thus the estimated cases are considered "accurate"?

RMSLE does not have general guideline regarding threshould (, but it is desireble the score is under 0.2 in my subjective opinion). The thresould should be the determined with the figure of `Scenario.history("Infected")` etc.

> For Germany the only data source I could find is interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit, but it seems there is no API/csv records.

Hmm... If the data of Wikipedia is reliable, we could notice COVID-19 Data Hub to correct the records.

**Comment by Inglezos** [comment] 2020-11-27 08:48
Does Wikipedia have an API/csv to extract such historical timeseries? Would be possible such a task for the COVID-19 Data Hub team to do?

I found a solution I think.
We could use directly the data from the Robert Koch Institut:
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4 (dashboard)
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html (daily reports in english)
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html (sources overview and info)
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0/data (source data file for new `DataLoader()` method).

Do you think it would be better to kindly notify the COVID-19 Data Hub team in order to fix this or we should create a new `DataLoader()` method for that?

**Comment by lisphilar** [comment] 2020-11-27 16:27
Thank you.
Wilipedia does not have API/csv and the primary sources is Robert Koch Institut database you mentioned.

If discrepancy of COVID-19 Data Hub and new dataset will not appear from tomorrow, we will notify the difference to COVID-19 Data Hub. If discrepancy will continue, it will be better to create a new method of `DataLoader` class not to put a burden on the team.

I found that COVID-19 Data Hub uses Robert Koch Institut database as the primary data source for Germany. We need to take time to compare the values with Robert Koch Institut database.
https://covid19datahub.io/articles/iso/DEU.html

**Comment by lisphilar** [comment] 2020-12-04 16:24
I found a dataset for Germany in GitHub. This will be also useful when we create a method for data loading because the scheme is similar to JHU data. However, recovered data is not registered and we need to use full complement system of recovered data.
https://github.com/jgehrcke/covid-19-germany-gae

**Comment by Inglezos** [comment] 2020-12-04 16:52
Why use full complement method, since

**Comment by Inglezos** [comment] 2020-12-04 17:08
So the problem with the Germany data is the fact that the recovered follow very close the confirmed and thus the infected are way too low, right? Which doesn't seem reasonable. Why can't we just keep the current source, the JHU CSSE and just fully complement the recovered?  I mean why do we need to change the source?

**Comment by lisphilar** [comment] 2020-12-04 17:09
I could not find solutions without raplacing the data source for Germany. How can we solve this issue with codes?

**Comment by Inglezos** [comment] 2020-12-04 17:23
We keep the confirmed and deaths data from JHU CSSE. We calculate closing period for recovered (a mix of the current implementation and the global linelist analysis I proposed for that) and generate fully complement recovered data produced by shifted confirmed, just like we currently do.
OR
We could keep the existing recovered data and shift them forward by closing period.

**Comment by lisphilar** [comment] 2020-12-05 11:15
Thank you for your ideas and solution 1 works.
However, these codes may complement when outbreak is ending.
When ending, `subset_df["Confirmed"].diff().diff() < 0` and `subset_df["Recovered"] > 0.99 * (subset_df["Confirmed"] - subset_df["Fatal"])` will be `True`.

What do you think about the following codes in pull request #380?
```Python

        c, f, r = subset_df[[self.C, self.F, self.R]].max().tolist()
        if r > max_ignored and r > (c - f) * 0.1:
            # Check if sum of recovered is more than 99%
            # of sum of recovered and infected when outbreaking
            sel_1 = subset_df[self.C] > max_ignored
            sel_2 = subset_df[self.C].diff().diff() > 0
            _df = subset_df.loc[sel_1 & sel_2]
            _df = _df.loc[_df[self.R] > 0.99 * (_df[self.C] - _df[self.F])]
            if _df.empty:
                return subset_df
```

(Please do not delete or edit your comments totally. When you have new ideas or update your ideas/questions, please add a new comment.)

**Comment by Inglezos** [comment] 2020-12-05 13:26
I approved the changes, this implementation solves the issue I think.

**Comment by lisphilar** [comment] 2020-12-05 14:12
Pull request #380 was merged because tests passed, but we need to discuss the new issue you mentioned here.
We need to find some coutries as examples, but I think full complement will not be performed when the second wave of outbreak occurs. This is because `_df[self.R]` will not be larger than `0.99 * (_df[self.C] - _df[self.F])`.

**Comment by Inglezos** [comment] 2020-12-05 14:17
Yes hopefully this condition secures this for us. Could we add a third condition about max_ignored for infected as well?

**Comment by lisphilar** [comment] 2020-12-05 14:25
We need to monitor list of countries where complement performed with #382.
Do you mean that we will add `min_infected_rate=0.1` to `._complement_recovered_full()` and `.subset_complement()` to replace `0.1` and `0.99`? Name of this argument needs discussion.

**Comment by lisphilar** [comment] 2020-12-09 13:20
Is `min_infected_rate` necessary?

**Comment by Inglezos** [comment] 2020-12-09 14:35
For now no it is not necessary, but in general it would add a more strict condition.
>{Inglezos): For example, if the pandemic is outbreaking, then it is almost diminished for some months and then again outbreaks (as happened in some countries in the summer), then this condition would indicate full compliment and would ignore the correct actual recovered records altogether.
>
In that case, the min_infected = 1000 for example perhaps could avoid wrong full complement during the second outbreak, in which case the two current conditions would be true. Of course this does not guarantee 100% that this will not happen. We have to investigate this when that happens or now with staged theoretical data and see the response.

**Comment by lisphilar** [comment] 2020-12-09 15:47
OK, we will close this issue to release 2.13, but we continue monitoring the effectivity and safety with #401.

**Closed by lisphilar** 2020-12-09 15:47 UTC
Labels: bug, enhancement
